---

- name: Install Jenkins 
  hosts: jenkinsserver
  remote_user: vagrant
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: yes

  vars:
    jenkins_version: "2.138.1"
    #jenkins_url: http://jenkins.example.com
    #jenkins_port: 80
    jenkins_install_via: "apt"
    jenkins_jobs:
        - "my-first-job"
        - "amigo"
        - "portal-stbwebre"
    jenkins_include_secrets: true
    jenkins_include_custom_files: true
    #jenkins_custom_files:
    #  - src: "jenkins.plugins.openstack.compute.UserDataConfig.xml"
    #    dest: "jenkins.plugins.openstack.compute.UserDataConfig.xml"
    #jenkins_custom_plugins:
    #    - "openstack-cloud-plugin/openstack-cloud.jpi"

  roles:
    - ansible-jenkins-os
  