---
- name: Create Jenkins group
  group:
    name: "{{ jenkins_config_group }}"
    state: present

- name: Create Jenkins user
  user:
    name: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    home: "{{ jenkins_home }}"
    shell: "/bin/false"
    state: present
    
- name: Grant permission to /data
  file: dest=/data mode=ugo+rw
    
- name: Install apt PPA dependencies
  apt:
    name: python-software-properties

- name: Install the Debian keyring
  apt:
    name: debian-archive-keyring

- name: Add Debian experimental repository for OpenJDK
  apt_repository:
    repo: deb http://httpredir.debian.org/debian experimental main
    state: present

- name: Add Debian sid repository for OpenJDK
  apt_repository:
    repo: deb http://httpredir.debian.org/debian sid main
    state: present

- name: Create pinning file for apt
  copy:
    src: files/apt/debian-package-pins
    dest: /etc/apt/preferences.d/debian
    owner: root
    group: root
    mode: 0644

- name: Install apt packages
  action: apt name={{ item }} state=present
  with_items: "{{ jenkins_apt_packages }}"

- name: Set default Java version
  shell: /usr/sbin/update-java-alternatives -s "{{ jenkins_java_version }}"
  ignore_errors: yes

- name: Add Jenkins key
  apt_key:
    url: "https://downloads.cloudbees.com/cloudbees-core/traditional/client-master/rolling/debian/cloudbees.com.key"
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb https://downloads.cloudbees.com/cloudbees-core/traditional/client-master/rolling/debian binary/'
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    
- name: Install Jenkins binary package
  apt:
    name: "cloudbees-core-cm"
    force: yes
    update_cache: yes

- name: Set JENKINS_HOME
  lineinfile:
    dest: /etc/default/cloudbees-core-cm
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='

- name: Set Jenkins port
  lineinfile:
    dest: /etc/default/cloudbees-core-cm
    regexp: '^HTTP_PORT='
    line: "HTTP_PORT={{ jenkins_port }}"

- name: Set Jenkins command line options
  lineinfile:
    dest: /etc/default/cloudbees-core-cm
    regexp: '^JAVA_ARGS='
    line: "JAVA_ARGS=\"{{ jenkins_java_opts }}\""

- name: Jenkins is running
  service:
    name: cloudbees-core-cm
    state: restarted

- pause: seconds=15
